### ISSUE TITLE
[BUG] Between some sections theres code showing up for a second 

### ISSUE THREAD

**Issue by Yanihero1** [TollyThaWally/The-Forest#2]
[2019-10-20 17-36-21.zip](https://github.com/TollyThaWally/The-Forest/files/3747965/2019-10-20.17-36-21.zip)
You can see how theres an empty code box inbetween some sections

**Comment by TollyThaWally** [comment]
Fill in the actual template for the issue

**Comment by TollyThaWally** [comment]
Will fix by adding a loading thing behind it

**Comment by TollyThaWally** [comment]
Can you check if the most recent release fixes it @Yanihero1 ?

**Comment by TollyThaWally** [comment]
This is a side effect of how the game runs and can't be fixed. Once the game is actually running it shouldn't happen
